### ISSUE TITLE
Teensy 3.2 and LC EOL 

### ISSUE THREAD

**Issue by jonnew** [open-ephys/commutators#11]
Both the Teensy LC and 3.2 are end of lifed. We will need to migrate to a different microcontroller option. Most MCUs don't come with integrated capacitive touch sensing. Additionally it has proven to be quite a difficult thing to get working reliably. However, it reducing design complexity and is appropriate for environments with animals. An option would be switching to some relatively generic MCU, e.g. RP2040 and adding an external cap sensor that hopefully takes care of the calibration issues for us. @aacuevas suggests the following: 

- https://ww1.microchip.com/downloads/aemDocuments/documents/OTH/ProductDocuments/DataSheets/00001571B.pdf

Microchip seems to have a family of those, which is a good thing for future-proofing. And it's a bit under a dollar and a half. In any case, it will need to be tested.

**Comment by jonnew** [comment]
Some measurements of GND referenced capacitance at on the V1.1 PCB

|   | 1 kHz   |
|---|---|
| LED Button  | 14 pF   | 
| Left Turn  |  51 pF | 
| Right Turn | 45 pF  | 
| Enable/Disable   | 42 pF  | 

This is right at the limit for the chip suggested above:

![image](https://github.com/user-attachments/assets/a6db75b4-fe4f-400c-8482-b05cc65772db)

Might be work decreasing this bit (e.g. by mesh filling the copy islands of the big buttons with ~50 fill density)

**Comment by cjsha** [comment]
Thanks for taking those measurements, I'll try the 50% mesh fill. That's also suggested by:
[Capacitive-Touch-Sensor-Design-Guide-DS00002934-B.pdf](https://github.com/user-attachments/files/17078185/Capacitive-Touch-Sensor-Design-Guide-DS00002934-B.pdf)
![Screenshot_20240920-123908](https://github.com/user-attachments/assets/18e2195d-66f2-4194-952a-0a322f52d42f)

**Comment by jonnew** [comment]
Nice, that guide is cool.
