### ISSUE TITLE
stop/go → enable/disable

### ISSUE THREAD

**Issue by cjsha** [open-ephys/commutators#2]
Should the button label "stop/go" change to "enable/disable"? My initial interpretation of the "stop/go" label doesn't match the actual function of the button. "enable/disable" might be more intuitive.

**Comment by jonnew** [comment]
Fixed in 6b259801f10eb22fa83777e8f2608b9c3601239d

**Comment by jonnew** [comment]
Fixed in 6b259801f10eb22fa83777e8f2608b9c3601239d
